### ISSUE TITLE
如何判断盒子出现在可视区域内——认识IntersectionObserver

### ISSUE THREAD

**Issue by coderRiki** [coderRiki/articles#3]
“如何判断盒子出现在可视区域内”，这是面试过程中常见的一个场景题，比如存在以下场景：

给出下列html和css，在滚动的过程中，判断红色盒子的**一半**是否出现在滚动区域内。

```html
 <div class="container">
    <div class="box red">red</div>
    <div class="box blue">blue</div>
    <div class="box green">green</div>
    <div class="box red">red</div>
</div>
```

```css
* {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
}

.container {
    width: 100%;
    height: 100%;
}

.box {
    width: 400px;
    height: 400px;
    margin: 0 auto;
    line-height: 400px;
    text-align: center;
    font-size: 24px;
    color: #fff;
}

.red {
    background-color: red;
}

.blue {
    background-color: blue;
}

.green {
    background-color: green;
}
```

![](https://cdn.nlark.com/yuque/0/2024/png/38426125/1727164502425-3441648d-390e-4b72-82c0-9509f2b93411.png)

该场景的解决思路有两种，第一种比较常规，也是最容易想到的，即监听`scroll`事件，利用`clientHeight`和`getBoundingClientRect`等属性，通过计算判断盒子是否在可视区域内；第二种做法是`IntersectionObserver`检测元素是否可见。

<h1 id="vyueA">使用getBoundingClientRect</h1>

MDN对于`getBoundingClientRect`的说明：

[https://developer.mozilla.org/zh-CN/docs/Web/API/Element/getBoundingClientRect](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/getBoundingClientRect)

+ 利用`document.documentElement.clientHeight`得到视口宽度`clientHeight`。
+ 监听`scroll`事件，调用`blueBox`的`getBoundingClientRect`方法，读取`height`属性，它记录了元素的高度，读取`top`属性，该属性表示盒子距离可视区域（屏幕）上边框的像素值。
+ 判断`-top <= height / 2`，若成立，则蓝盒子一半区域在可视区域内。

```javascript
let clientHeight = document.documentElement.clientHeight;
let blueBox = document.querySelector('.blue');
let offsetTop = blueBox.offsetTop;
window.addEventListener('scroll', () => {
  let blueBoxRect = blueBox.getBoundingClientRect();
  let {
    height,
    top
  } = blueBoxRect;
  let scrollTop = document.documentElement.scrollTop;
  if (-top <= height / 2) {
    console.log('蓝盒子一半在可视区域内')
  }
})
```

以上方法都在主线程上运行，即使是其中的一行代码也会导致性能问题。

此外，**每一次滚动都会触发回调函数**。

<h1 id="vqniw">使用IntersectionObserver</h1>

将一个回调函数传给`IntersectionObserver`API，当特定元素进入或者退出它和另一元素的交集时，或者两个元素之间的交集发生指定变化时，该函数就会被执行。

监视元素交集变化的任务不需要主线程负责，而是交给浏览器来管理。

MDN对`Intersection Observer`的说明：

[https://developer.mozilla.org/zh-CN/docs/Web/API/Intersection_Observer_API#%E8%A7%84%E8%8C%83](https://developer.mozilla.org/zh-CN/docs/Web/API/Intersection_Observer_API#%E8%A7%84%E8%8C%83)

```javascript
let options = {
    root: document, // 用作视口的元素，用于检测目标的可见性
    threshold: [0.5] // 表示交叉比
}
let observer = new IntersectionObserver((entries, observer) => {
    entries.forEach((entry) => {
        let {
            isIntersecting // 表示交集是否触发
        } = entry;
        if (isIntersecting) {
            console.log('一半在可视区域内')
        }
    })
}, options);
let blueBox = document.querySelector('.blue');
// 设置需要观察的元素
observer.observe(blueBox);
```

**只有当满足交集条件时才会触发回调函数**。

使用场景：

1. 图片懒加载；
2. 虚拟列表（无限滚动）；

<h1 id="HHQaQ">相关阅读</h1>

[[IntersectionObserver](https://juejin.cn/post/7148038337318617125?searchId=202409241503002692BD20539BC86307E3#heading-12)](https://juejin.cn/post/7148038337318617125?searchId=202409241503002692BD20539BC86307E3#heading-12)
